// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB34dL8ggL_jIPyQEi9Fqq5m-MRXqabgHs",
    authDomain: "proyecto1-4445d.firebaseapp.com",
    projectId: "proyecto1-4445d",
    storageBucket: "proyecto1-4445d.appspot.com",
    messagingSenderId: "259832549649",
    appId: "1:259832549649:web:a9827bd2fb1e41b1013cb0",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB34dL8ggL_jIPyQEi9Fqq5m-MRXqabgHs",
    appId: "1:259832549649:android:a9827bd2fb1e41b1013cb0",
    messagingSenderId: "259832549649",
    projectId: "proyecto1-4445d",
    storageBucket: "proyecto1-4445d.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB34dL8ggL_jIPyQEi9Fqq5m-MRXqabgHs",
    appId: "1:259832549649:ios:a9827bd2fb1e41b1013cb0",
    messagingSenderId: "259832549649",
    projectId: "proyecto1-4445d",
    storageBucket: "proyecto1-4445d.appspot.com",
    iosBundleId: "com.example.rc.proyectoPersonal",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB34dL8ggL_jIPyQEi9Fqq5m-MRXqabgHs",
    appId: "1:259832549649:ios:a9827bd2fb1e41b1013cb0",
    messagingSenderId: "259832549649",
    projectId: "proyecto1-4445d",
    storageBucket: "proyecto1-4445d.appspot.com",
    iosBundleId: "com.example.rc.proyectoPersonal",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyB34dL8ggL_jIPyQEi9Fqq5m-MRXqabgHs",
    appId: "1:259832549649:web:a9827bd2fb1e41b1013cb0",
    messagingSenderId: "259832549649",
    projectId: "proyecto1-4445d",
    authDomain: "proyecto1-4445d.firebaseapp.com",
    storageBucket: "proyecto1-4445d.appspot.com",
    measurementId: "G-GXJHVWW451",
  );
}
